title: "HR & Legal School"
description: "Курсы повышения квалификации для юристов и кадровиков"
url: "https://demo.hrlegalschool.kz"
baseurl: ""
remote_theme: "cotes2020/jekyll-theme-chirpy"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Навигация и страницы
nav:
  - title: "О нас"
    url: /about/
  - title: "Наши семинары"
    url: /seminars/
  - title: "Контакты"
    url: /contact/

# Custom head (_includes/head_custom.html)
include:
  - _includes/head_custom.html

# Custom domain
cname: demo.hrlegalschool.kz